name: Automated Data Preprocessing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Muhammad_Faiz_Munif_Billah.py

      - name: Commit processed dataset
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add preprocessing/namadataset_preprocessing/titanic_clean.csv
          git commit -m "Automated preprocessing update" || echo "No changes to commit"
          git push
